# Exported from Render on 2024-05-19T08:49:29Z
services:
- type: web
  name: shoes-shop-api
  runtime: node
  repo: https://github.com/nqmgaming/shoes-shop-api
  plan: free
  envVars:
  - key: CLOUDINARY_URL
    sync: false
  - key: CLOUDINARY_SECRET_KEY
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: ACCESS_TOKEN_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: yarn
  startCommand: npm run start
  domains:
  - www.nqmgaming.nl
  - nqmgaming.nl
version: "1"
